# yaml-language-server: $schema=../../../doc/schemas/default-config.json#web
# yaml-language-server: $schema=https://raw.githubusercontent.com/yeagerai/genvm/refs/heads/main/doc/schemas/default-config.json#web
bind_address: 127.0.0.1:3032
webdriver_host: http://127.0.0.1:4444

lua_script_path: ${exeDir}/../config/genvm-web-default.lua
vm_count: 6
lua_path: ${exeDir}/../lib/genvm-lua/?.lua
signer_url: "#{signerUrl}"
signer_headers: {}

threads: 4
blocking_threads: 16
log_disable: ""
#log_level: trace

session_create_request: |
  {
    "capabilities": {
      "alwaysMatch": {
        "browserName": "firefox",
        "moz:firefoxOptions": {
          "args": [
            "--headless"
          ]
        }
      }
    }
  }

extra_tld: []
always_allow_hosts: []
