# yaml-language-server: $schema=../../../doc/schemas/default-config.json#genvm
# yaml-language-server: $schema=https://raw.githubusercontent.com/yeagerai/genvm/refs/heads/main/doc/schemas/default-config.json#genvm
modules:
  llm:
    address: ws://127.0.0.1:3031
  web:
    address: ws://127.0.0.1:3032

threads: 2
blocking_threads: 4
log_disable: wasmtime*,cranelift*,tracing*,polling*,tungstenite*,tokio_tungstenite*,genvm::memlimiter*

cache_dir: ${exeDir}/../.cache/
runners_dir: ${exeDir}/../../../runners/
registry_dir: ${exeDir}/../data
