name: GenVM initial checks
on:
  workflow_call:

env:
  GCS_BUCKET: "gh-af"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get source
        uses: ./.github/actions/get-src
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85.1
          components: rustfmt
          cache: false
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure
