name: Build Release For Target

on:
  workflow_call:
    inputs:
      target:
        description: 'Target to build'
        required: true
        type: string
      secondary_target:
        description: 'Secondary target to build'
        required: false
        type: string
        default: ''
      executor_version:
        description: 'Version name of the executor'
        required: true
        type: string
      bundle_extra:
        description: 'Extra bundle to include in the build'
        required: false
        type: string
        default: ''
    secrets:
      GCP_SA_KEY:
        description: 'Google Cloud Service Account Key'
        required: true
    outputs:
      artifact_url:
        description: "URL to download the built artifact"
        value: ${{ jobs.build.outputs.artifact_url }}
      secondary_artifact_url:
        description: "URL to download the secondary built artifact"
        value: ${{ jobs.build.outputs.secondary_artifact_url }}

env:
  GCS_BUCKET: "gh-af"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    outputs:
      artifact_url: ${{ steps.upload.outputs.gcs_url }}
      secondary_artifact_url: ${{ steps.upload.outputs.secondary_gcs_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get source
        uses: ./.github/actions/get-src
        with:
          load_submodules: "false"
          with_nix: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Extra
        if: ${{ inputs.bundle_extra != '' }}
        run: |
          echo "Downloading extra bundle: ${{ inputs.bundle_extra }}"
          curl -fsSL -o extra.tar.xz "${{ inputs.bundle_extra }}"
          xz -d extra.tar.xz

      - name: Build
        run: |
          ./support/ci/pipelines/build.sh \
            --target ${{ inputs.target }} \
            --executor-version ${{ inputs.executor_version }} \
            $(if [ "${{ inputs.bundle_extra }}" != "" ]; then echo "--extra-bundle extra.tar"; fi)

      - name: Build Secondary
        if: ${{ inputs.secondary_target != '' }}
        run: |
          ./support/ci/pipelines/build.sh \
            --target ${{ inputs.secondary_target }} \
            --executor-version ${{ inputs.executor_version }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Generate upload url
        id: upload
        run: |
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          DIR_NAME="genvm_executor_${GITHUB_SHA}_${TIMESTAMP}"
          echo "dirname=$DIR_NAME" >> $GITHUB_OUTPUT
          BASE_NAME="genvm-${{ inputs.target }}.tar.xz"
          echo "basename=$BASE_NAME" >> $GITHUB_OUTPUT
          echo "gcs_url=https://storage.googleapis.com/$GCS_BUCKET/$DIR_NAME/$BASE_NAME" >> $GITHUB_OUTPUT

          if [ "${{ inputs.secondary_target }}" != "" ]; then
            SECONDARY_BASE_NAME="genvm-${{ inputs.secondary_target }}.tar.xz"
            echo "secondary_basename=$SECONDARY_BASE_NAME" >> $GITHUB_OUTPUT
            echo "secondary_gcs_url=https://storage.googleapis.com/$GCS_BUCKET/$DIR_NAME/$SECONDARY_BASE_NAME" >> $GITHUB_OUTPUT
          else
            echo "secondary_basename=" >> $GITHUB_OUTPUT
            echo "secondary_gcs_url=" >> $GITHUB_OUTPUT
          fi

      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: build/${{ steps.upload.outputs.basename }}
          destination: ${{ env.GCS_BUCKET }}/${{ steps.upload.outputs.dirname }}
          parent: false

      - name: Upload Secondary to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        if: ${{ inputs.secondary_target != '' }}
        with:
          path: build/${{ steps.upload.outputs.secondary_basename }}
          destination: ${{ env.GCS_BUCKET }}/${{ steps.upload.outputs.dirname }}
          parent: false
