name: GenVM pr
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
defaults:
  run:
    shell: bash -x {0}

jobs:
  initial:
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'test:skip:pr') }}
    uses: ./.github/workflows/initial-template.yaml
    secrets: inherit

### MODULE TESTS

  module-test-python:
    needs: [initial]
    runs-on: ubuntu-latest
    if: needs.initial.outputs.py-changed == 'true'
    permissions:
      pull-requests: write   # Needed for posting a comment
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: Gr1N/setup-poetry@v9
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: poetry
      - name: Get source
        uses: ./.github/actions/get-src
        with:
          load_submodules: "false"
      - name: install dependencies
        run: |
          pushd runners/genlayer-py-std && \
            poetry install && \
            popd
      - name: pytest
        run: |
          pushd runners/genlayer-py-std && \
          echo "_(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_" > /tmp/py-cov.log && \
          echo '```' >> /tmp/py-cov.log && \
          poetry run pytest -n auto | tee -a /tmp/py-cov.log && \
          echo '```' >> /tmp/py-cov.log && \
          popd
      - name: report
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: /tmp/py-cov.log
          comment-tag: py-coverage

### END

  validate-end:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - initial
      - module-test-python
    steps:
      - name: check
        if: ${{ !contains( github.event.pull_request.labels.*.name, 'test:skip:pr') }}
        run: |
          echo ${{ join(needs.*.result, ' ') }} | grep -vP 'failure|cancelled'
